[project]
authors = ["Curro Campuzano <campuzanocurrogmail.com>"]
channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"]
description = "Implementation of popular genomic offset statistics"
name = "genomic-offsets-vanilla"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
genomic_offsets = { path = "." }

[package]
name = "genomic_offsets"
version = "0.1.2"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
numdifftools = ">=0.9.41,<0.10"
numba = ">=0.61.0,<0.62"
numpy = ">=2.1.3,<3"
scipy = ">=1.15.1,<2"
rpy2 = ">=3.5.11,<4"
statsmodels = ">=0.14.4,<0.15"
