# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/genomic-offsets',
                'doc_host': 'https://currocam.github.io',
                'git_url': 'https://github.com/currocam/genomic-offsets',
                'lib_path': 'genomic_offsets'},
  'syms': {'genomic_offsets.core': {'genomic_offsets.core.foo': ('core.html#foo', 'genomic_offsets/core.py')}}}
