"""Geometric genomic offset"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_geometric.ipynb.

# %% auto 0
__all__ = ['GeometricGO', 'genetic_gap']

# %% ../nbs/04_geometric.ipynb 3
from .RidgeLFMM import *
from fastcore.utils import *
import statsmodels.api as sm
from nbdev.showdoc import *
from numba import njit, jit
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

# %% ../nbs/04_geometric.ipynb 5
class GeometricGO:
    "Geometric genomic offset statistic."
    def __init__(self, 
                 K: int, # Number of latent factors 
                 lambd: float): # Regularization parameter
        self.K = K
        self.lambd = lambd
        self._LFMM = None
        self._mx = None
        self._sx = None
        self.Cb = None
    def __str__(self):
        return f"Geometric genomic offset with K={self.K} and lambda={self.lambd}"
    __repr__ = __str__

# %% ../nbs/04_geometric.ipynb 9
@patch
def fit(self:GeometricGO,
        Y: np.ndarray, # Genotype matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the Geometric genomic offset model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    # Scale data and save it to predict later
    Y = Y - np.mean(Y, axis=0)
    mx = np.mean(X, axis=0)
    X = X - mx
    sx = np.std(X, axis=0)
    X = X / sx
    self._mx = mx
    self._sx = sx
    model = self._LFMM = RidgeLFMM(K=self.K, lambd=self.lambd)
    model.fit(Y=Y, X=X)
    self.Cb = np.dot(model.B.T, model.B) / model.B.shape[0]

# %% ../nbs/04_geometric.ipynb 19
@patch
def _rescale_env(self:GeometricGO,
        X: np.ndarray, # Environmental matrix (nxP)
        )-> np.ndarray: # A vector of genomic offsets (n)
    if self._mx is None or self._sx  is None: 
        raise ValueError("You have to fit the model first!")
    return (X-self._mx) / self._sx 

# %% ../nbs/04_geometric.ipynb 20
@patch
def predict(self:GeometricGO,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the *centered* optimal genotypes for the fitted environmental matrix."
    X = self._rescale_env(X)
    return self._LFMM.predict(X)

# %% ../nbs/04_geometric.ipynb 24
@njit
def genetic_gap(Cb: np.ndarray, X: np.ndarray, Xstar: np.ndarray) -> np.ndarray:
    offsets = np.zeros(X.shape[0])
    for i in range(len(offsets)):
        diff = X[i, :] - Xstar[i, :]
        offsets[i] = np.dot(np.dot(diff, Cb), diff.T)
    return offsets

# %% ../nbs/04_geometric.ipynb 25
@patch
def genomic_offset(self:GeometricGO,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Calculates the genomic offset statistic. " 
    if X.shape != Xstar.shape: 
        raise ValueError("Dimensions of array don't match")
    return genetic_gap(self.Cb, self._rescale_env(X), self._rescale_env(Xstar))
