"""Redundancy analysis genomic offset"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_RDA.ipynb.

# %% auto 0
__all__ = ['RDA']

# %% ../nbs/02_RDA.ipynb 4
class RDA:
    "Redundancy analysis genomic offset statistic."
    def __init__(self, K: int):
        self._reg = None
        self._pca = None
        self.K = K
    def __str__(self):
        return f"Redundancy analysis model with K={self.K}"
    __repr__ = __str__

# %% ../nbs/02_RDA.ipynb 8
@patch
def fit(self:RDA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the RDA model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    X = sm.add_constant(X)
    model = sm.OLS(Y, X)
    self._reg = model.fit()
    self._pca = sm.PCA(self._reg.predict(X), ncomp=self.K, method="nipals")

# %% ../nbs/02_RDA.ipynb 13
@patch
def predict(self:RDA,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the projected alleles for a given environmental matrix."
    X = sm.add_constant(X)
    return np.dot(self._reg.predict(X), self._pca.loadings)

# %% ../nbs/02_RDA.ipynb 16
@patch
def genomic_offset(self:RDA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Calculates the genomic offset statistic. " 
    if X.shape != Xstar.shape: 
        raise ValueError("Dimensions of array don't match")
    offset = np.zeros(X.shape[0])
    diff = self.predict(X) - self.predict(Xstar)
    weights = self._pca.eigenvals / np.sum(self._pca.eigenvals)
    L = self._reg.params.shape[1]
    for distance, w in zip(diff.T, weights):
        offset += distance**2*w/L
    return offset
    
