"""Redundancy analysis genomic offset"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_RDA.ipynb.

# %% auto 0
__all__ = ['RDA', 'partial_RDA']

# %% ../nbs/03_RDA.ipynb 5
class RDA:
    "Redundancy analysis genomic offset statistic."
    def __init__(self, K: int):
        self._reg = None
        self._pca = None
        self.K = K
    def __str__(self):
        return f"Redundancy analysis model with K={self.K}"
    __repr__ = __str__

# %% ../nbs/03_RDA.ipynb 9
@patch
def fit(self:RDA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the RDA model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    X = sm.add_constant(X)
    model = sm.OLS(Y, X)
    self._reg = model.fit()
    self._pca = sm.PCA(self._reg.predict(X), ncomp=self.K, method="nipals")

# %% ../nbs/03_RDA.ipynb 19
@patch
def predict(self:RDA,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the projected alleles for a given environmental matrix."
    X = sm.add_constant(X)
    return np.dot(self._reg.predict(X), self._pca.loadings)

# %% ../nbs/03_RDA.ipynb 24
@patch
def genomic_offset(self:RDA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Calculates the genomic offset statistic. " 
    if X.shape != Xstar.shape: 
        raise ValueError("Dimensions of array don't match")
    offset = np.zeros(X.shape[0])
    diff = self.predict(X) - self.predict(Xstar)
    weights = self._pca.eigenvals / np.sum(self._pca.eigenvals)
    L = self._reg.params.shape[1]
    for distance, w in zip(diff.T, weights):
        offset += distance**2*w/L
    return offset
    

# %% ../nbs/03_RDA.ipynb 37
class partial_RDA:
    "Redundancy analysis genomic offset statistic."
    def __init__(self, K: int):
        self._mod = None
        self._reg_X = None
        self._reg_residuals = None
        self._pca = None
        self.K = K
    def __str__(self):
        return f"Partial redundancy analysis model with K={self.K}"
    __repr__ = __str__

# %% ../nbs/03_RDA.ipynb 41
@patch
def fit(self:partial_RDA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray, # Environmental matrix (nxP)
        W: np.ndarray): # Covariate matrix (nxZ)
    "Fits the partial RDA model. "
    n1, L = Y.shape
    n2, P = X.shape
    n3, Z = W.shape
    if n1 != n2 or n1 != n3: 
        raise ValueError("Dimensions of array don't match")
    W = sm.add_constant(W)
    self._reg_X = sm.OLS(X, W).fit()
    residuals_Y = sm.OLS(Y, W).fit().resid.reshape(Y.shape)
    residuals_X = sm.add_constant(self._reg_X.resid.reshape(X.shape))
    self._reg_residuals = sm.OLS(residuals_Y,  residuals_X).fit()
    self._pca = sm.PCA(self._reg_residuals.predict(residuals_X), ncomp=self.K, method="nipals")

# %% ../nbs/03_RDA.ipynb 45
@patch
def predict(self:partial_RDA,
        X: np.ndarray, # Environmental matrix (nxP)
        W: np.ndarray # Covariate matrix (nxZ)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the projected alleles for a given environmental matrix."
    W = sm.add_constant(W)
    residuals_X = (X - self._reg_X.predict(W).reshape(X.shape))
    residuals_X = sm.add_constant(residuals_X)
    pred_residuals_Y = self._reg_residuals.predict(residuals_X)
    return np.dot(pred_residuals_Y, self._pca.loadings)

# %% ../nbs/03_RDA.ipynb 49
@patch
def genomic_offset(self:partial_RDA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
        W: np.ndarray # Covariate matrix (nxZ)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Calculates the genomic offset statistic. " 
    if X.shape != Xstar.shape: 
        raise ValueError("Dimensions of array don't match")
    if X.shape[0] != W.shape[0]: 
        raise ValueError("Dimensions of array don't match")
    offset = np.zeros(X.shape[0])
    diff = self.predict(X, W) - self.predict(Xstar, W)
    weights = self._pca.eigenvals / np.sum(self._pca.eigenvals)
    L = self._reg_residuals.params.shape[1]
    for distance, w in zip(diff.T, weights):
        offset += distance**2*w/L
    return offset
