# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_RDA.ipynb.

# %% auto 0
__all__ = ['RDA']

# %% ../nbs/02_RDA.ipynb 4
class RDA:
    "Redundancy analysis genomic offset statistic."
    def __init__(self, K: int):
        self._reg = LinearRegression(copy_X=True, fit_intercept=True)
        self._pca = PCA(n_components=K)
    def __str__(self):
        return "Redundancy analysis model"
    __repr__ = __str__

# %% ../nbs/02_RDA.ipynb 8
@patch
def fit(self:RDA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the RDA model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    self._reg.fit(X, Y)
    self._pca.fit(self._reg.predict(X))

# %% ../nbs/02_RDA.ipynb 13
@patch
def predict(self:RDA,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the allele frequencies for a given environmental matrix. "    
    return self._pca.transform(self._reg.predict(X))

# %% ../nbs/02_RDA.ipynb 16
@patch
def genomic_offset(self:RDA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Predicts the allele frequencies for a given environmental matrix. " 
    if X.shape != Xstar.shape: 
        raise ValueError("Dimensions of array don't match")
    offset = np.zeros(X.shape[0])
    diff = self.predict(X) - self.predict(Xstar)
    weights = self._pca.explained_variance_ / np.sum(self._pca.explained_variance_ )
    L = model._reg.coef_.shape[0]
    for distance, w in zip(diff.T, weights):
        offset += distance**2*w/L
    return offset
    
