"""Ridge solutions to a Latent factor mixed model"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_LFMM.ipynb.

# %% auto 0
__all__ = ['RidgeLFMM', 'lfmm2', 'latent_factors_with_TracyWidom']

# %% ../nbs/06_LFMM.ipynb 3
from fastcore.utils import *
import statsmodels.api as sm
from nbdev.showdoc import *
from scipy.linalg import svd, inv
from scipy.stats import f
from TracyWidom import TracyWidom
from numba import njit, jit
from collections import namedtuple
from rpy2.robjects.packages import importr
from rpy2.robjects import numpy2ri
from rpy2.robjects import default_converter
import numpy as np
import matplotlib.pyplot as plt

# %% ../nbs/06_LFMM.ipynb 5
class RidgeLFMM:
    "Ridge solutions to a Latent Factor Mixed Model (LFMM)."    
    def __init__(self, 
                 K: int, # Number of latent factors 
                 lambd: float): # Regularization parameter
        self.U, self.V, self.B = None, None, None
        self.K = K
        self.lambd = lambd
    def __str__(self):
        "Returns a string representation of the RidgeLFMM instance."
        return f"RidgeLFMM model with K={self.K} and lambda={self.lambd}"
    __repr__ = __str__

# %% ../nbs/06_LFMM.ipynb 9
def lfmm2(Y, X, K, lambd=1e-5, center=True):
    # Assumes data has been already centered
    n, p = X.shape
    # Singular Value Decomposition (SVD) of X
    Q, sigma, _ = svd(X, overwrite_a=True)
    # Create the diagonal matrix D
    d = np.ones(n)
    d_inv = np.ones(n)
    # R implementation doesn't use square sigma
    # although I think the paper does
    d[:p] = np.sqrt(lambd / (lambd + sigma))
    d_inv[:p] = np.sqrt((lambd + sigma) / lambd)
    #d[:p] = np.sqrt(lambd / (lambd + sigma**2))
    #d_inv[:p] = np.sqrt((lambd + sigma**2) / lambd)
    D = np.diag(d)
    Dinv = np.diag(d_inv)
    # SVD of the modified Y (D * Q.T * Y)
    U_svd, S_svd, Vt_svd = svd(np.dot(D, np.dot(Q.T, Y)), full_matrices=False)
    # Get first K components from SVD
    U = np.dot(np.dot(Q, Dinv), U_svd[:, :K]) * S_svd[:K]
    Vt = Vt_svd[:K, :]
    # Ridge regression to compute Bt
    Bt = np.linalg.inv(np.dot(X.T, X) + lambd * np.eye(p)).dot(X.T).dot(Y - np.dot(U, Vt))
    return U, Vt.T, Bt.T

# %% ../nbs/06_LFMM.ipynb 10
@patch
def fit(self:RidgeLFMM,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the LFMM model. It a"
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    Y = Y - np.mean(Y, axis=0)
    X = X - np.mean(X, axis=0)
    self.U, self.V, self.B = lfmm2(Y, X, self.K, self.lambd)


# %% ../nbs/06_LFMM.ipynb 18
@patch
def predict(self:RidgeLFMM,
        X: np.ndarray): # Environmental matrix (nxP)
    "Predicts the centered genotypes for a given environmental matrix."
    X = X - np.mean(X, axis=0)
    return X @ self.B.T + self.U@self.V.T

# %% ../nbs/06_LFMM.ipynb 27
def latent_factors_with_TracyWidom(
        twstat: np.ndarray, # Tracy-Widom statistics
        thresholds: np.ndarray # Array of significance levels
        ) -> int: # Number of significant eigenvalues
    n = len(thresholds)
    res = np.zeros(n)
    for i in range(n):
        pvalues = 1- TracyWidom(beta=1).cdf(twstat)
        indices = np.where(pvalues > thresholds[i])[0]
        if len(indices) == 0:
            res[i] = len(pvalues)
            pass
        else:
            res[i] = max(indices[0] - 1, 0)
    return res

# %% ../nbs/06_LFMM.ipynb 31
@patch
def FTest(self:RidgeLFMM,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray, # Environmental matrix (nxP)
        genomic_control: bool=True, # whether to use genomic control
         ) -> np.ndarray: # Array of p-values (L) 
    "Re-fit the coefficient of the LFMM model and make an F-test."
    Y = Y - np.mean(Y, axis=0)
    X = X - np.mean(X, axis=0)
    n, d = X.shape
    U = np.hstack([np.ones((n, 1)), self.U])
    U_inv_Y = np.linalg.lstsq(U, Y, rcond=None)[0]
    res_Y = Y - U @ U_inv_Y
    res_X = X - U @ np.linalg.lstsq(U, X, rcond=None)[0]
    res_X = np.hstack([np.ones((n, 1)), res_X])
    fitted = res_X @ np.linalg.lstsq(res_X, res_Y, rcond=None)[0]
    mss = np.sum(np.abs(fitted) ** 2, axis=0)
    resvar = np.sum(np.abs(res_Y - fitted) ** 2, axis=0) / (n - d - 1)
    #resvar = np.maximum(resvar, 1e-10)  # Numerical stability
    Fscores = mss / (d * resvar)
    dist = f(d, n - d - 1)   
    if genomic_control:
        gif = np.median(Fscores) / dist.ppf(0.5)
        pvalues = 1 - dist.cdf(Fscores / gif)
    else:
        pvalues = 1 - dist.cdf(Fscores)
    return Fscores, np.ravel(pvalues)
