"""Ridge solutions to a Latent factor mixed model"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_LFMM.ipynb.

# %% auto 0
__all__ = ['RidgeLFMM', 'latent_factors_with_TracyWidom']

# %% ../nbs/03_LFMM.ipynb 5
class RidgeLFMM:
    "Ridge solutions to a Latent Factor Mixed Model (LFMM)."    
    def __init__(self, 
                 K: int, # Number of latent factors 
                 lambd: float): # Regularization parameter
        self.U, self.V, self.B = None, None, None
        self.K = K
        self.lambd = lambd
    def __str__(self):
        "Returns a string representation of the RidgeLFMM instance."
        return f"RidgeLFMM model with K={self.K} and lambda={self.lambd}"
    __repr__ = __str__

# %% ../nbs/03_LFMM.ipynb 10
@patch
def fit(self:RidgeLFMM,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the LFMM model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    Y = Y - np.mean(Y, axis=0)
    X = X - np.mean(X, axis=0)
    self.U, self.V, self.B = lfmm2(Y, X, self.K, self.lambd)


# %% ../nbs/03_LFMM.ipynb 24
def latent_factors_with_TracyWidom(
        twstat: np.ndarray, # Tracy-Widom statistics
        thresholds: np.ndarray # Array of significance levels
        ) -> int: # Number of significant eigenvalues
    n = len(thresholds)
    res = np.zeros(n)
    for i in range(n):
        pvalues = 1- TracyWidom(beta=1).cdf(twstat)
        indices = np.where(pvalues > thresholds[i])[0]
        if len(indices) == 0:
            res[i] = len(pvalues)
            pass
        else:
            res[i] = max(indices[0] - 1, 0)
    return res

# %% ../nbs/03_LFMM.ipynb 28
@patch
def FTest(self:RidgeLFMM,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray, # Environmental matrix (nxP)
        genomic_control: bool=True, # whether to use genomic control
         ) -> np.ndarray: # Array of p-values (L) 
    "Re-fit the coefficient of the LFMM model and make an F-test."
    Y = Y - np.mean(Y, axis=0)
    X = X - np.mean(X, axis=0)
    n, d = X.shape
    U = np.hstack([np.ones((n, 1)), self.U])
    U_inv_Y = np.linalg.lstsq(U, Y, rcond=None)[0]
    res_Y = Y - U @ U_inv_Y
    res_X = X - U @ np.linalg.lstsq(U, X, rcond=None)[0]
    res_X = np.hstack([np.ones((n, 1)), res_X])
    fitted = res_X @ np.linalg.lstsq(res_X, res_Y, rcond=None)[0]
    mss = np.sum(np.abs(fitted) ** 2, axis=0)
    resvar = np.sum(np.abs(res_Y - fitted) ** 2, axis=0) / (n - d - 1)
    #resvar = np.maximum(resvar, 1e-10)  # Numerical stability
    Fscores = mss / (d * resvar)
    dist = f(d, n - d - 1)   
    if genomic_control:
        gif = np.median(Fscores) / dist.ppf(0.5)
        pvalues = 1 - dist.cdf(Fscores / gif)
    else:
        pvalues = 1 - dist.cdf(Fscores)
    return Fscores, np.ravel(pvalues)
