# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_RONA.ipynb.

# %% auto 0
__all__ = ['RONA']

# %% ../nbs/01_RONA.ipynb 4
class RONA:
    "Risk of non-adaptedness genomic offset statistic."
    def __init__(self): 
        self._reg = LinearRegression(copy_X=True, fit_intercept=True)
    def __str__(self):
        return "RONA model."
    __repr__ = __str__

# %% ../nbs/01_RONA.ipynb 8
@patch
def fit(self:RONA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the RONA model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    self._reg.fit(X, Y)

# %% ../nbs/01_RONA.ipynb 13
@patch
def predict(self:RONA,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the allele frequencies for a given environmental matrix. "    
    return self._reg.predict(X)


# %% ../nbs/01_RONA.ipynb 16
@patch
def genomic_offset(self:RONA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Predicts the allele frequencies for a given environmental matrix. "
    L = model._reg.coef_.shape[0]
    if X.shape != Xstar.shape:
        raise ValueError("Dimensions of array don't match")
    return np.sum(np.abs(self._reg.predict(X) - self._reg.predict(Xstar)), axis=1) / L
