# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_RONA.ipynb.

# %% auto 0
__all__ = ['RONA']

# %% ../nbs/01_RONA.ipynb 4
class RONA:
    "Risk of non-adaptedness genomic offset statistic."
    def __init__(self): 
        self.B = None
    def __str__(self):
        if self.B is None: 
            return "RONA model. Please, fit me first using the `fit()` method."
        else: 
            p, l = self.B.shape
            return f"RONA model. Fitted with {p-1} environmental covariates and {l} alleles."
    __repr__ = __str__

# %% ../nbs/01_RONA.ipynb 8
@patch
def fit(self:RONA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the RONA model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    X = np.hstack((np.ones((X.shape[0], 1)), X)) 
    B = np.linalg.lstsq(X, Y)[0]
    self.B = B

# %% ../nbs/01_RONA.ipynb 13
@patch
def predict(self:RONA,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the allele frequencies for a given environmental matrix. "    
    B = self.B
    if X.shape[1] != (B.shape[0]-1):
        raise ValueError("Dimensions of array don't match")
    X = np.hstack((np.ones((X.shape[0], 1)), X)) 
    return X@B

# %% ../nbs/01_RONA.ipynb 16
@patch
def genomic_offset(self:RONA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Predicts the allele frequencies for a given environmental matrix. "    
    B = self.B
    if X.shape != Xstar.shape:
        raise ValueError("Dimensions of array don't match")
    X = np.hstack((np.ones((X.shape[0], 1)), X)) 
    Xstar = np.hstack((np.ones((Xstar.shape[0], 1)), Xstar)) 
    return np.sum(np.abs(X @ self.B - Xstar @ self.B), axis=1) / model.B.shape[1]
