"""Risk of non-adaptedness"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_RONA.ipynb.

# %% auto 0
__all__ = ['RONA']

# %% ../nbs/02_RONA.ipynb 5
class RONA:
    "Risk of non-adaptedness genomic offset statistic."
    def __init__(self): 
        self._reg = None
    def __str__(self):
        return "RONA model."
    __repr__ = __str__

# %% ../nbs/02_RONA.ipynb 9
@patch
def fit(self:RONA,
        Y: np.ndarray, # Allele frequency matrix (nxL)
        X: np.ndarray): # Environmental matrix (nxP)
    "Fits the RONA model. "
    n1, L = Y.shape
    n2, P = X.shape
    if n1 != n2: 
        raise ValueError("Dimensions of array don't match")
    X = sm.add_constant(X)
    model = sm.OLS(Y, X)
    self._reg = model.fit()

# %% ../nbs/02_RONA.ipynb 17
@patch
def predict(self:RONA,
        X: np.ndarray # Environmental matrix (nxP)
           )-> np.ndarray: # Predicted allele frequencies
    "Predicts the allele frequencies for a given environmental matrix. "    
    return self._reg.predict(sm.add_constant(X))


# %% ../nbs/02_RONA.ipynb 21
@patch
def genomic_offset(self:RONA,
        X: np.ndarray, # Environmental matrix (nxP)
        Xstar: np.ndarray, # Altered environmental matrix (nxP)
           )-> np.ndarray: # A vector of genomic offsets (n)
    "Calculates the genomic offset statistics. "
    L = self._reg.params.shape[1]
    X, Xstar = sm.add_constant(X), sm.add_constant(Xstar)
    if X.shape != Xstar.shape:
        raise ValueError("Dimensions of array don't match")
    return np.sum(np.abs(self._reg.predict(X) - self._reg.predict(Xstar)), axis=1) / L
