name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: r-lib/actions/setup-r@v2
      - name: Test with nbdev + R dependencies
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -U nbdev
          echo "Doing editable install..."
          test -f setup.py && pip install -e ".[dev]"
          echo "Intall R dependencies ..."
          Rscript -e 'install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/devel/%s/%s/%s",.Platform$pkgType, R.Version()$os, R.Version()$arch))'
          Rscript -e 'pak::pak(c("gradientForest", "LEA"))'
          echo "Check we are starting with clean git checkout"
          if [[ `git status --porcelain -uno` ]]; then
            git diff
            echo "git status is not clean"
            false
          fi
          echo "Trying to strip out notebooks"
          nbdev_clean
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [[ `git status --porcelain -uno` ]]; then
            git status -uno
            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
            echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
            false
          fi
          nbdev_export
          if [[ `git status --porcelain -uno` ]]; then
            echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
            git status -uno
            git diff
            exit 1;
          fi
          nbdev_test
          fi
